### ISSUE TITLE
Issues on Conditional

### ISSUE THREAD

**Issue by gerard-pcom** [iGovPhil/igovphil.github.io#1] opened 2019-04-25 09:33 UTC
On [pst/gwtpst.js](https://github.com/iGovPhil/igovphil.github.io/blob/master/pst/gwtpst.js) [line 44]:
` if(typeof this.element == 'null'){`

Since typeof of null is object, shouldn't this be:
`if(this.element == 'null'){`

On line 80:
`if(response = func()){` instead of a condition, there is declaration, so should it be:
`if(response == func()){`

**Comment by v0j** [comment] 2019-06-13 02:19
Hi Gerard,

I appreciate sending ticket issue.

Regarding line 80:
It was coded as intended to be. The ```func``` argument is a function that returns a response. In order to retrieve the response, we assigned it into a variable ```response``` AND also test if there is a response from the function at the same time. Its a shorthand of variable assignment and condition.

This can be rewritten into:

```
response = func();
// test if there is a response from the argument
if(response){

}
```

**Comment by v0j** [comment] 2019-06-13 02:38
With regards to line 44. The ```this.element``` is a direct callback of ```document.getElementById()``` in which if there is no found element it will return a null value. So the condition works as intended as well.

I'll close this ticket for now. Let me know if you found anything that needs reviewing.

Thank you,

**Closed as completed by v0j** 2019-06-13 02:38 UTC

**Comment by gerard-pcom** [comment] 2019-06-14 10:52
Thank you for the clarification. I was trying to add gwtpst.js to a custom
template and ESLint couldn't compile.
Anyway, thank you again.
